### ISSUE TITLE
FormEncoder needs a Map<String,Any> but the example show (@Param, @param)

### ISSUE THREAD

**Issue by vvvrrooomm** [OpenFeign/feign-form#35]
The FormEncoder.encode (FormEncoder.java:86) tests if the given parameter is a Map<String,?> but the README.md shows void from (@Param("field1") String field1, @Param("field2") String field2);
In Feign more than one @Param is not even allowed. 
Did I miss something, is the documentation wrong or is the test too strict??

**Comment by xxlabaza** [comment]
I didn't get your question, sorry.

Multiple @param arguments are allowed., you could check the tests, for example:
https://github.com/OpenFeign/feign-form/blob/master/feign-form/src/test/java/feign/form/TestClient.java#L67

I am checking Map<Strimg, ?> to be sure what a method has arguments and it has the correct content type, otherwise - delegate will process it.

**Comment by stoetti** [comment]
Follow-Up question
When used in a Spring Boot application I get the following error on startup
`Caused by: java.lang.IllegalStateException: Method has too many Body parameters: public abstract feign.Response com.applications.observer.clients.CockpitClient.authenticateCockpit(java.lang.String,java.lang.String)
	at feign.Util.checkState(Util.java:128) ~[feign-core-9.5.0.jar:na]
	at feign.Contract$BaseContract.parseAndValidateMetadata(Contract.java:114) ~[feign-core-9.5.0.jar:na]
	at org.springframework.cloud.netflix.feign.support.SpringMvcContract.parseAndValidateMetadata(SpringMvcContract.java:133) ~[spring-cloud-netflix-core-1.4.2.RELEASE.jar:1.4.2.RELEASE]
	at feign.Contract$BaseContract.parseAndValidatateMetadata(Contract.java:64) ~[feign-core-9.5.0.jar:na]
	at feign.ReflectiveFeign$ParseHandlersByName.apply(ReflectiveFeign.java:146) ~[feign-core-9.5.0.jar:na]
	at feign.ReflectiveFeign.newInstance(ReflectiveFeign.java:53) ~[feign-core-9.5.0.jar:na]
	at feign.Feign$Builder.target(Feign.java:218) ~[feign-core-9.5.0.jar:na]
	at org.springframework.cloud.netflix.feign.HystrixTargeter.target(HystrixTargeter.java:39) ~[spring-cloud-netflix-core-1.4.2.RELEASE.jar:1.4.2.RELEASE]
	at org.springframework.cloud.netflix.feign.FeignClientFactoryBean.loadBalance(FeignClientFactoryBean.java:211) ~[spring-cloud-netflix-core-1.4.2.RELEASE.jar:1.4.2.RELEASE]
	at org.springframework.cloud.netflix.feign.FeignClientFactoryBean.getObject(FeignClientFactoryBean.java:232) ~[spring-cloud-netflix-core-1.4.2.RELEASE.jar:1.4.2.RELEASE]
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:168) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	... 35 common frames omitted`

What am I missing?

Here is a snippet of my Interface
`@FeignClient(value = "cockpit", configuration = CockpitClient.FeignFormConfiguration.class)
public interface CockpitClient {

    class FeignFormConfiguration {

        @Autowired
        private ObjectFactory<HttpMessageConverters> messageConverters;

        @Bean
        public Encoder feignFormEncoder() {
            return new SpringFormEncoder(new SpringEncoder(messageConverters));
        }

    }

    @PostMapping(path = Constants.COCKPIT_AUTH_URL, consumes = MediaType.APPLICATION_FORM_URLENCODED_VALUE)
    Response authenticateCockpit(@Param("username") String username, @Param("password") String password);

}`

**Comment by xxlabaza** [comment]
Hi!

You mixed annotations from different [contract](https://github.com/OpenFeign/feign/blob/master/core/src/main/java/feign/Contract.java) implementations.

Feign uses *contract* abstraction for parsing annotations for your interface's methods.

**@Param** - annotation for [Default](https://github.com/OpenFeign/feign/blob/master/core/src/main/java/feign/Contract.java#L195) contract parser;

**@PostMapping** - annotation for [SpringMvcContract](https://github.com/spring-cloud/spring-cloud-netflix/blob/2c502e3997eaca84eb8c4198fa6f3bd45cf49bba/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/feign/support/SpringMvcContract.java).

When you use **Spring Boot** with **Feign** you implicitly use autoconfiguration, which setup SpringMvcContract, so default annotations (like @Param) don't work.

P.S.: btw, **@PostMapping** annotation doesn't work with SpringMvcContract too, because of...I don't know...laziness of spring developers? Use regular **@RequestMapping** (take a look at my tests for examples)
