### ISSUE TITLE
Problem integrating feign with slf4j

### ISSUE THREAD

**Issue by hellboy81** [OpenFeign/feign-form#58]
```java
java.lang.LinkageError: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of org/apache/felix/framework/BundleWiringImpl$BundleClassLoaderJava5) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of org/apache/catalina/loader/WebappClassLoader) for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:332)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:280)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:301)
	at feign.form.multipart.SingleFileWriter.<clinit>(SingleFileWriter.java:32)
	at feign.form.MultipartFormContentProcessor.<init>(MultipartFormContentProcessor.java:67)
	at feign.form.FormEncoder.<init>(FormEncoder.java:73)
```

**Comment by hellboy81** [comment]
```java
cause=java.lang.NoClassDefFoundError: Could not initialize class feign.form.multipart.SingleFileWriter, stacktrace=java.lang.NoClassDefFoundError: Could not initialize class feign.form.multipart.SingleFileWriter

feign.form.MultipartFormContentProcessor.<init>(MultipartFormContentProcessor.java:67) [?:?]

at feign.form.FormEncoder.<init>(FormEncoder.java:73) [?:?]
```

**Comment by hellboy81** [comment]
In OSGI: lombok: version: 0, resolution: optional

**Comment by hellboy81** [comment]
```java

java.lang.LinkageError: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of org/apache/felix/framework/BundleWiringImpl$BundleClassLoaderJava5) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of org/apache/catalina/loader/WebappClassLoader) for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature, stacktrace=java.lang.LinkageError: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of org/apache/felix/framework/BundleWiringImpl$BundleClassLoaderJava5) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of org/apache/catalina/loader/WebappClassLoader) for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature

[INFO] org.codehaus.cargo.maven2.ContainerStartMojo - [talledLocalContainer]     	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:332) [slf4j-api-1.7.9.jar:1.7.9]

[INFO] org.codehaus.cargo.maven2.ContainerStartMojo - [talledLocalContainer]     	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:280) [slf4j-api-1.7.9.jar:1.7.9]

[INFO] org.codehaus.cargo.maven2.ContainerStartMojo - [talledLocalContainer]     	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:301) [slf4j-api-1.7.9.jar:1.7.9]

[INFO] org.codehaus.cargo.maven2.ContainerStartMojo - [talledLocalContainer]     	at feign.form.multipart.SingleFileWriter.<clinit>(SingleFileWriter.java:32) [?:?]

[INFO] org.codehaus.cargo.maven2.ContainerStartMojo - [talledLocalContainer]     	at feign.form.MultipartFormContentProcessor.<init>(MultipartFormContentProcessor.java:67) [?:?]

[INFO] org.codehaus.cargo.maven2.ContainerStartMojo - [talledLocalContainer]     	at feign.form.FormEncoder.<init>(FormEncoder.java:73) [?:?]
````
