### ISSUE TITLE
Support with Content-Type multipart/form-data

### ISSUE THREAD

**Issue by gasperlf** [OpenFeign/feign-form#73]
**Controller**
```
public ResponseEntity<Respuesta<String>> leerCodigoBarras(@RequestParam("file") MultipartFile archivo) {   
      //logic
}
```

**Feing interface**
```
@RequestMapping(path=END_POINT,method= RequestMethod.POST,consumes = MULTIPART_FORM_DATA_VALUE)
    ResponseEntity<Respuesta<String>> leerCodigoBarras(@RequestParam("file") MultipartFile archivo);
```

Configuration class for Feing Interface

```
@Configuration
public class ServiceClientConfig {
    
	    @Autowired
	    private ObjectFactory<HttpMessageConverters> messageConverters;

	    @Bean
	    public Encoder feignFormEncoder() {
	        return new SpringFormEncoder(new FormEncoder(new SpringEncoder(messageConverters)));
	    }
	    
	    @Bean
        public feign.Logger.Level multipartLoggerLevel() {
            return feign.Logger.Level.FULL;
        }
	}
```

When request get at the controller i get that error

```
org.apache.tomcat.util.http.fileupload.FileUploadException: the request was rejected because no multipart boundary was found
        at org.apache.tomcat.util.http.fileupload.FileUploadBase$FileItemIteratorImpl.<init>(FileUploadBase.java:831)
        at org.apache.tomcat.util.http.fileupload.FileUploadBase.getItemIterator(FileUploadBase.java:256)
        at org.apache.tomcat.util.http.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:280)
        at org.apache.catalina.connector.Request.parseParts(Request.java:2884)
        at org.apache.catalina.connector.Request.parseParameters(Request.java:3232)
        at org.apache.catalina.connector.Request.getParameter(Request.java:1137)
        at org.apache.catalina.connector.RequestFacade.getParameter(RequestFacade.java:381)
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:75)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1468)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Unknown Source)
```
and that is because `MultipartFormContentProcessor` in the method process is not working in the execution, in that method add:

```
val contentTypeHeaderValue = new StringBuilder()
        .append(getSupportedContentType().getHeader())
        .append("; charset=").append(charset.name())
        .append("; boundary=").append(boundary)
        .toString();
```

anyone know why happend that?

**Comment by martinlosak** [comment]
Try @RequestPart("file") MultipartFile archivo

**Comment by hhhyde** [comment]
> Try @RequestPart("file") MultipartFile archivo

it worked for me,  thanks
