### ISSUE TITLE
java.lang.NoSuchFieldError: MAP_STRING_WILDCARD

### ISSUE THREAD

**Issue by DanielHit** [OpenFeign/feign-form#8]
when I  use  FormEncoder like this:
```java
        TestClient gwClient = Feign.builder().options(new Request.Options(CONNECT_TIMEOUT_MILLIS, READ_TIMEOUT_MILLIS))
                .encoder(new FormEncoder())
                .decoder(new GsonDecoder())
                .target(TestClient.class, rpcConfig.getGwUrl());
```
There is a error:
```
java.lang.NoSuchFieldError: MAP_STRING_WILDCARD

	at feign.form.FormEncoder.encode(FormEncoder.java:98)
	at feign.ReflectiveFeign$BuildEncodedTemplateFromArgs.resolve(ReflectiveFeign.java:252)
	at feign.ReflectiveFeign$BuildTemplateByResolvingArgs.create(ReflectiveFeign.java:199)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:67)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:94)
	at com.sun.proxy.$Proxy142.createCebBankCode(Unknown Source)
```

Then, I get the source code FormEncoder, find：
```
        if (bodyType != MAP_STRING_WILDCARD) {
            deligate.encode(object, bodyType, template);
            return;
        }
```
the `MAP_STRING_WILDCARD` not found to be Initialize?

**Comment by xxlabaza** [comment]
which feign-core version do you use?

**Comment by DanielHit** [comment]
the feign-core version is 8.1.0

**Comment by xxlabaza** [comment]
Ok, just update the version to at least 8.1.6. It has feign.codec.Encoder.MAP_STRING_WILDCARD and everything should be fine

**Comment by DanielHit** [comment]
ok, thanks!
